修复删除节点后孩子节点扔参与递归比较
viclm/jquery-widget pull request #2
Opened 2016-09-09 07:24 UTC by ansenAC

对于这样的diff
oldTree:
<div>
    <div class="panel-wrapper>
        <div class="path"></div>
    </div>
    <div class="panel-wrapper>
        <div class="path"></div>
    </div>
</div>

newTree
<div>
    <span class="edit">
    </span>
    <label><label>
</div>

在diff第一个panel-wrapper时，你在domTree中删除了该节点，但该节点仍有childNodes,因此下一步的patch.walk方法中，this.patches记录的是label节点，而node传入的是panel-wrapper的孩子结点path。造成diff出错。

2016-09-13 09:28 UTC, viclm commented
1. 请在spec/patch.js补充测试用例
2. 感觉修改略复杂

2016-09-13 09:39 UTC, viclm commented
请在spec/patch.js补充测试用例

2016-09-13 09:40 UTC, viclm commented on src/virtual-dom/patch.js
>          if (this.patchesRemaining > 0 && (node === this.root[0] || node && node.nodeType === 1 && !$.data(node, 'widget'))) {
node && nodeType === 1 && !node. replaceComplete &&

2016-09-14 02:23 UTC, ansenAC commented on src/virtual-dom/patch.js
>          if (this.patchesRemaining > 0 && (node === this.root[0] || node && node.nodeType === 1 && !$.data(node, 'widget'))) {
对，isDetached语义更好一些 ，单独拉出来做逻辑判断是不想侵入源代码。

2016-09-16 09:51 UTC, viclm requested changes
改一下吧

2016-09-18 07:04 UTC, viclm approved these changes

2016-09-18 07:08 UTC, merged